/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function condHashBranch(lowBound: bigint, highBound: bigint, testValue: number, salt: Buffer): bigint

export declare function condInvolutePacket(packet: Buffer, involuteSalt: Buffer, chunkSize: number, lowBound: bigint, highBound: bigint, testValue: number): Buffer

export declare function cyclePacket(packet: Buffer, oldSalt: Buffer, newSalt: Buffer, oldKey: Buffer, newKey: Buffer, chunkSize: number): Buffer

export declare function genKey(partyId: string, purpose: string, masterSeed: Buffer): Buffer

export declare function getChunkSize(packet: Buffer): number

export declare function getChunkSizeMin(packet: Buffer, minSize: number): number

export declare function invData(pubKey: Buffer, privKeys: Array<Buffer>, dataSequences: Array<Buffer>): Array<Buffer>

export declare function involutePacket(packet: Buffer, salt: Buffer, chunkSize: number): Buffer

export declare function mapData(pubKey: Buffer, privKey: Buffer, identity: number, dataSequence: Array<Buffer>): Buffer

export declare function packageBlob(buffers: Array<Buffer>, mode: string, identity: number): Buffer

export declare function prepCondition(lowBound: number, highBound: number, salt: Buffer): [bigint, bigint]

export declare function unpackEncryptedPacket(data: Buffer): [Buffer, Buffer, Buffer, string, bigint]

export declare function unpackSetupPacket(data: Buffer): [Buffer, Buffer, string, bigint]
